chore: Add instructions on usage for dotnet and python
DevCycleHQ/devcycle-docs pull request #379
Opened 2023-08-18 19:36 UTC by JamieSinn

2023-08-21 14:01 UTC, jonathannorris requested changes
Can we split this off into its own docs page?

2023-08-22 14:09 UTC, jonathannorris commented on docs/sdk/local-bucketing-proxy/index.md
> +![Server SDK Topology](/server-sdk-topology.svg)
These SVGs are very large: 
<img width="1764" alt="image" src="https://github.com/DevCycleHQ/devcycle-docs/assets/1219069/c4197941-5fa7-41e8-b181-52ffcd772b11">

2023-08-29 22:16 UTC, chris-hoefgen commented
On the SDK home page the `Local Bucket Proxy` section should be updated to be `SDK Proxy` and probably link to that set of documentation

2023-09-05 19:26 UTC, cdruxerman approved these changes
I've taken a few reviews of the preview site, I'm good with the current status to go live and edit further after feedback in the wild.

2023-09-05 19:31 UTC, merged